apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: YWRtaW4= # "admin"
  mongo-root-password: YW5raXRwYXRlbDAyMA== # "ankitpatel020"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb://admin:ankitpatel020@mongo-service:27017/lcit_herbal_store?authSource=admin"
  JWT_SECRET: "lcit_herbal_store_secret_key_2024_chemistry_dept"
  JWT_EXPIRE: "30d"
