apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: YWRtaW4=
  mongo-root-password: U1RST05HX1BBU1NXT1JE
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb://admin:STRONG_PASSWORD@mongo-service:27017/lcit_herbal_store?authSource=admin"
  JWT_SECRET: "strong_super_secret_key_change_me_in_prod"
  JWT_EXPIRE: "30d"
